### ISSUE TITLE
Compiling error OpenSUSE 42.1 - libgtk-3.so: undefined references

### ISSUE THREAD

**Issue by cbcoutinho** [jerryd/gtk-fortran#104]
I have been having trouble installing gtk-fortran (gtk3 branch) on my Linux machine (openSUSE 42.1 Leap). I keep running into linking errors associated with my installed gtk library, of which I have installed gtk3 with development headers.

The error occurs when attempting to link an executable. This occurs for _every_ executable:

```
/usr/lib64/libgtk-3.so: undefined reference to `g_list_model_get_type'
/usr/lib64/libgdk-3.so: undefined reference to `cairo_surface_set_device_scale'
/usr/lib64/libgtk-3.so: undefined reference to `g_list_model_get_n_items'
/usr/lib64/libgtk-3.so: undefined reference to `g_file_enumerator_iterate'
/usr/lib64/libgdk-3.so: undefined reference to `cairo_surface_get_device_scale'
/usr/lib64/libgtk-3.so: undefined reference to `g_list_model_get_item'
```

I tried making gtk-fortran without any flags, as well as with the `-i` flag described in the wiki - that isn't solving the problem. As far as I understand it, that flag is only getting around an error associated with a couple example problems. The error I'm experiencing doesn't build a single example.

I copied the `cmake` output, `make` output, and `make -i` output into a gist.

[See the (c)make output here](https://gist.github.com/cbcoutinho/4435133527c17a014d730d4de5406dde).

**Comment by vmagnin** [comment]
OK. Have you also installed libglib2.0-dev and libcairo2-dev ?

In fact, GTK+ depends on some other libraries like GLib and Cairo (also GDK, GdkPixbuf, Pango, ATK, GObject, GIO). See:
https://developer.gnome.org/gtk3/stable/gtk.html

Add every *-dev needed when you see "undefined reference" errors. And please tell me which ones: I will update the Wiki page. In my Ubuntu distribution, when I install libgtk-3-dev, all the other *-dev on which it depends are installed. Perhaps it is not the case in your openSUSE ?

**Comment by cbcoutinho** [comment]
Wow thanks for the help - I just built gtk-fortran on my system without any issues using the master branch (still only gtk2?) as well as the gtk3 branch - both without problems. 

The missing dependencies were related to GdkPixbug: libgtkimageview0 and gtkimageview-devel on openSUSE 42.1 Leap. They could be named differently on other versions of openSUSE.

I didn't get any errors related to missing include directories, so this seemed to have solved the other issue related to that `make -i` workaround

**Comment by vmagnin** [comment]
Well ! On my Ubuntu, libgtkimageview0 is installed but not gtkimageview-dev.

Yes, the master branch is still GTK+2 for historical reasons. But users should of course use the gtk3 branch.
