### ISSUE TITLE
Gtk/Gtk-Fortan and xls etc files

### ISSUE THREAD

**Issue by DrOli** [jerryd/gtk-fortran#106]
We have written some basic Fortran to read/write spreadsheet files (SSF's).  

Some SSF formats are rather more involved, such as .xls.  While we would normal build our own from scratch, this is a sufficiently big issue to consider alternatives.  We are testing a number of libs for this as well as, such as LibXL, POI, and various "sub libs" used in OpenOffice etc.

So far all of the third party libs etc that we have seen are in Java, C, or TCL.  Have you any thoughts on read/write .xls and possibly .xlsx (or even "lesser" formats like SYLK) with Fortran?

**Comment by vmagnin** [comment]
The easiest way is probably to use iso_c_binding to link your Fortran program with a C library. I know there is some Python libraries to write in Open Document Format (odfpy for example). Python libraries being generally written in C, it should be possible to call them from Fortran 2003. You could then use an ods to xls converter. It seems libreoffice has a --convert-to option. I don't know if it works with xls.

But ODS and XLSX being XML formats, may be you can also use something like  http://xml-fortran.sourceforge.net/.
