### ISSUE TITLE
Strange GtkClipoard Excel SIGSEGV/crash

### ISSUE THREAD

**Issue by DrOli** [jerryd/gtk-fortran#110]
This is not actually a gtk-fortran "only/specific" matter, as it can be (100%) reproduced with C.  As such, we accept that it is a bit cheeky to submit it here, and would understand if the submission was removed.

Still, it is just so weird a Gtk issue, any help/guesses would be appreciated.  Instead of cluttering your blog, the matter has been detailed as a StackOverflow question (including code, images, etc) here (http://stackoverflow.com/questions/40730454/gtkclipboard-gdk-property-delete-targets-crash-excel-only-windows).

**Comment by vmagnin** [comment]
Closed because the link does not exist anymore. Don't hesitate to reopen is the problem persists.
