### ISSUE TITLE
Unable to run the demo example given in the documentation

### ISSUE THREAD

**Issue by johnsamuelwrites** [jerryd/gtk-fortran#125]
Following the instructions under the section ['Linux'](https://github.com/jerryd/gtk-fortran/wiki), I encountered errors 

<pre>
$ gfortran gtk.f90 ../examples/julia_pixbuf.f90 `pkg-config --cflags --libs gtk+-3.0`
gtk.f90:61:8:

     use g, only: g_signal_connect_data
        1
Fatal Error: Can't open module file ‘g.mod’ for reading at (1): No such file or directory
compilation terminated.
../examples/julia_pixbuf.f90:39:6:

   use gtk, only: gtk_container_add, gtk_drawing_area_new, gtk_events_pending, gtk&
      1
Fatal Error: Can't open module file ‘gtk.mod’ for reading at (1): No such file or directory
compilation terminated.
</pre>

There were no compilation errors and the application was successfully installed.

For details on the review process, refer: https://github.com/openjournals/joss-reviews/issues/1014

**Comment by vmagnin** [comment]
Dear John Samuel,

yes, some files were missing in the gfortran compilation command. I have updated the wiki documentation as follows:
> And if you know which gtk-fortran files are needed, you can also simply compile and run each example as follow, from the src/ directory:
> ```bash
> $ gfortran glib-auto.f90 cairo-auto.f90 gdk-auto.f90 gdk-pixbuf-auto.f90 gtk.f90 ../examples/julia_pixbuf.f90 `pkg-config --cflags --libs gtk+-2.0`
> $ ./a.out
> ```
> (please replace 2.0 by 3.0 in the gtk3 branch).

**Comment by johnsamuelwrites** [comment]
Thanks for the changes. The example is now working.
