### ISSUE TITLE
gtk-fortran with Pathscale EKOPath 4

### ISSUE THREAD

**Issue by bonanza** [jerryd/gtk-fortran#31]
The EKOPath 4 compiler suite is now released as open source (http://www.pathscale.com/ekopath4-open-source-announcement) and can be downloaded from github (https://github.com/path64/compiler).

I tried to compile gtk-fortran with the pathf95 Fortran compiler, which resulted in a cascade of errors. The first one produces the following message:

<pre>
GTK_SCROLLABLE_SET_HADJUSTMENT
  Pgm_Unit                  Not_Referenced            IDX             = 21815   
  AT_ACCESS_SET   = F       AT_ACTUAL_ARG   = F       AT_PROTECTED    = F       
  AT_ARG_TO_KIND  = F       AT_ATTR_LINK    = 0       AT_CIF_DONE     = F       
  AT_CIF_IN_USAGE_= F       AT_CIF_SYMBOL_ID= 0       AT_CIF_USE_IN_BN= F       
  AT_COMPILER_GEND= F       AT_DCL_ERR      = F       AT_DEF_COLUMN   = 12      
  AT_DEF_LINE     = 25880   AT_DEF_IN_CHILD = F       AT_DEFINED      = F       
  AT_ELEMENTAL_INT= F       AT_HOST_ASSOCIAT= F       AT_IGNORE_ATTR_L= F       
  AT_IS_DARG      = F       AT_IS_INTRIN    = F       AT_LOCKED_IN    = F       
  AT_MODULE_IDX   = 0       AT_MODULE_OBJECT= F       AT_NAME_LEN     = 30      
  AT_NAMELIST_OBJ = F       AT_NOT_VISIBLE  = F       AT_ORIG_MODULE_I= 0       
  AT_ORIG_NAME_LEN= 0       AT_ORIG_NAME_IDX= 0
  AT_OPTIONAL     = F       AT_PRIVATE      = Public  AT_REF_IN_CHILD = F       
  AT_SEMANTICS_DON= T       AT_TYPED        = F       AT_USE_ASSOCIATE= F       
  Subroutine                Extern_Proc               ATP_ALIGN       = F       
  ATP_ALL_INTENT_I= F       ATP_ALT_ENTRY   = F       ATP_ARGCHCK_CALL= F       
  ATP_ARGCHCK_ENTR= F       ATP_DCL_EXTERNAL= F       ATP_DUPLICATE_IN= 0       
  AT_BIND_ATTR    = T       ATP_PP_ABSTRACT = F       ATP_PP_PROTO    = T      
  ATP_ELEMENTAL   = F       ATP_ENTRY_LABEL_= 0       ATP_EXPL_ITRFC  = T       
  ATP_EXT_NAME_IDX= 80294   ATP_EXT_NAME_LEN= 30      gtk_scrollable_set_hadjustment
  ATP_EXTERNAL_INT= F       ATP_EXTRA_DARG  = F       ATP_FIRST_IDX   = 12302   
  ATP_FIRST_SH_IDX= 0       ATP_GLOBAL_ATTR_= 19188  
  ATP_HAS_ALT_RET = F       ATP_HAS_OVER_IND= F       ATP_HAS_TASK_DIR= F       
  ATP_IN_INTERFACE= T       ATP_IN_UNNAMED_I= T       ATP_INLINE_ALWAY= F       
  ATP_INLINE_NEVER= F       ATP_MAY_INLINE  = F       ATP_NAME_IN_STON= F       
  ATP_NO_ENTRY_LIS= 0       ATP_NON_ANSI_INT= F       ATP_NOSIDE_EFFEC= F       
  ATP_NUM_DARGS   = 2       ATP_OPTIONAL_DIR= F       ATP_PARENT_IDX  = 469     
  ATP_PURE        = F       ATP_RECURSIVE   = F      
  ATP_RSLT_IDX    = 0       ATP_SAVE_ALL    = F       ATP_SCP_ALIVE   = F       
  ATP_SCP_IDX     = 1       ATP_SGI_RTN_INL = F       ATP_SGI_RTN_NOIN= F       
  ATP_SGI_GLB_INL = F       ATP_SGI_GLB_NOIN= F       ATP_SGI_LOC_INL = F       
  ATP_SGI_LOC_NOIN= F       ATP_STACK_DIR   = F       ATP_SYMMETRIC   = F       
  ATP_TASK_SHARED = F       ATP_USES_EREGS  = F       ATP_VFUNCTION   = F       

  Dummy Arguments for GTK_SCROLLABLE_SET_HADJUSTMENT:

  SCROLLABLE                                                      IDX = 12302   
  SN_COLUMN_NUM   = 43      SN_LINE_NUM     = 25880   SN_NAME_LEN     = 10      
  SN_NAME_IDX     = 80290   SN_ATTR_IDX     = 21816   SN_SIBLING_LINK = 0       
  ATD_ARRAY_IDX   = 0       ATD_POINTER     = F       ATD_TYPE_IDX    = 2848    
  ATD_PE_ARRAY_IDX= 0       

  HADJUSTMENT                                                     IDX = 12303   
  SN_COLUMN_NUM   = 55      SN_LINE_NUM     = 25880   SN_NAME_LEN     = 11      
  SN_NAME_IDX     = 80292   SN_ATTR_IDX     = 21817   SN_SIBLING_LINK = 0       
  ATD_ARRAY_IDX   = 0       ATD_POINTER     = F       ATD_TYPE_IDX    = 2848    
  ATD_PE_ARRAY_IDX= 0       

pathf95-42 pathf95: INTERNAL GTK_INIT, File = gtk.f90, Line = 95, Column = 7 
  Attribute entry 21815 has a variant problem with field ATD_PP_ATP.
Signal: Aborted in Front End Parse/Semantic phase.
Error: Signal Aborted in phase Front End Parse/Semantic -- processing aborted
</pre>

**Comment by vmagnin** [comment]
I close that issue because it is an old post, but don't hesitate to reopen if the problem persists.
