### ISSUE TITLE
Fedora 16 and Mac OS X problems

### ISSUE THREAD

**Issue by vmagnin** [jerryd/gtk-fortran#56]
Four emails received from Angelo:

---

I have tried to build current jerryd-gtk-fortran-4f369b4, and on Fedora 16
with gcc 4.6.3 it fails. I did this

cd jerryd-gtk-fortran-4f369b4
mkdir build
cd build
cmake ..
make
[...]
Scanning dependencies of target hl_list1
[ 80%] Building Fortran object
examples/CMakeFiles/hl_list1.dir/hl_list1.f90.o
Linking Fortran executable hl_list1
../src/libgtk-2-fortran.a(gtk-hl-tree.f90.o): In function
`__gtk_hl_tree_MOD_hl_gtk_list_tree_get_gvalue':
gtk-hl-tree.f90:(.text+0xe53): undefined reference to`g_value_get_schar'
gtk-hl-tree.f90:(.text+0xe80): undefined reference to `g_value_get_schar'
gtk-hl-tree.f90:(.text+0xeb1): undefined reference to`g_value_get_schar'
gtk-hl-tree.f90:(.text+0xedb): undefined reference to `g_value_get_schar'
gtk-hl-tree.f90:(.text+0xf04): undefined reference to`g_value_get_schar'
../src/libgtk-2-fortran.a(gtk-hl-tree.f90.o): In function
`__gtk_hl_tree_MOD_hl_gtk_list_tree_set_gvalue':
gtk-hl-tree.f90:(.text+0x2280): undefined reference to`g_value_set_schar'
gtk-hl-tree.f90:(.text+0x22a7): undefined reference to `g_value_set_schar'
gtk-hl-tree.f90:(.text+0x22d5): undefined reference to`g_value_set_schar'
gtk-hl-tree.f90:(.text+0x22fe): undefined reference to `g_value_set_schar'
gtk-hl-tree.f90:(.text+0x2327): undefined reference to`g_value_set_schar'
collect2: ld returned 1 exit status
make[2]: **\* [examples/hl_list1] Error 1
make[1]: **\* [examples/CMakeFiles/hl_list1.dir/all] Error 2
make: **\* [all] Error 2

So I tried with a previous version (august 2012),
jerryd-gtk-fortran-fcfa718 and it worked.

It worked also installing in a different directory,

cmake -DCMAKE_INSTALL_PREFIX=/home/graziosi/applications/gtk.fortran ..

Notice : ..._PREFIX and not ..._DIR as described in the INSTALL file.

After this, I needed to define:

export
PKG_CONFIG_PATH=/home/graziosi/applications/gtk.fortran/lib/pkgconfig

but trying,

gfortran -O3 -J ./modules basic_mods.f90 shading.f90 mandelbrot_CM.f90
`pkg-config --cflags --libs gtk-2-fortran` -o mandelbrot_CM.out2
/usr/bin/ld: cannot find -lgtk-2-fortran
collect2: ld returned 1 exit status

there was a problem.

It was fixed adding the path to the library,

gfortran -O3 -J ./modules basic_mods.f90 shading.f90 mandelbrot_CM.f90 -L
../gtk.fortran/lib `pkg-config --cflags --libs gtk-2-fortran` -o
mandelbrot_CM.out2

this worked!

The question is: should `pkg-config --cflags --libs gtk-2-fortran` be
enough to find the library?

Notice that I can omit the -I .../gtk.fortran/include/gtk-2-fortran
option..

**Comment by jessica-brown** [comment]
I'm trying to use gtk-frotran on Mac OS X El Capitan. I am having the same error (copied below) as above - I was wondering if there was actually a solution for it? 

$ cd build/
$ cmake ..
-- The Fortran compiler identification is GNU 6.1.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Build type is: release
-- Found GTK2_GTK: /opt/local/lib/libgtk-x11-2.0.dylib
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.1")
-- Could NOT find PLPLOT (missing:  PLPLOT_LIBRARIES)
-- PLPLOT not found: PLPLOT integration and examples will not be built
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   gtk-fortran_shared

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/ascii/Downloads/gtk-fortran-master/build
$ make
Scanning dependencies of target gtk-fortran_shared
[  1%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/glib-auto.f90.o
[  2%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gdk-auto.f90.o
[  3%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk.f90.o
[  4%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-accelerator.f90.o
[  5%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/unixonly-auto.f90.o
[  6%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-assistant.f90.o
[  6%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-sup.f90.o
[  7%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-misc.f90.o
[  8%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-button.f90.o
[  9%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-container.f90.o
[ 10%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-entry.f90.o
[ 10%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-chooser.f90.o
[ 11%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-combobox.f90.o
[ 12%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-dialog.f90.o
[ 12%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-infobar.f90.o
[ 13%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-menu.f90.o
[ 14%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-progress.f90.o
[ 15%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-spin-slider.f90.o
[ 15%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gdk-pixbuf-auto.f90.o
[ 15%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl-tree.f90.o
[ 16%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/cairo-auto.f90.o
[ 17%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/atk-auto.f90.o
[ 18%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gdk-pixbuf-hl.f90.o
[ 18%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gdkevents-auto2.f90.o
[ 19%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-draw-hl.f90.o
[ 19%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk-hl.f90.o
[ 20%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/pango-auto.f90.o
[ 21%] Linking Fortran shared library libgtk-2-fortran.dylib
ld: illegal text-relocation to '_hl_gtk_tree_rtoggle_cb' in CMakeFiles/gtk-fortran_shared.dir/gtk-hl-tree.f90.o from 'anon' in CMakeFiles/gtk-fortran_shared.dir/gtk-hl-tree.f90.o for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/libgtk-2-fortran.0.1.dylib] Error 1
make[1]: *** [src/CMakeFiles/gtk-fortran_shared.dir/all] Error 2
make: *** [all] Error 2

(Hope this is the right place to put this - first time using github)

**Comment by vmagnin** [comment]
Hi Jessica,
I am not familiar with MacOS but I will try to help you. Do you know the exact version of the GTK+ library on your system ? It seems there is a linking problem between gtk-hl-tree.f90 and GTK+. It seems the problem is in the function hl_gtk_tree_rtoggle_cb (line 2180) in gtk-hl-tree.f90.

In the source of gtk-hl-tree.f90, I read it was designed for GTK+ 2.24.0. If ever your version is <2.24, is it possible for you to install a more recent one ?

I have tried to search for "illegal text-relocation":
https://duckduckgo.com/?q=%22illegal+text-relocation
but it seems specific to the Mac linker.

Vincent

**Comment by vmagnin** [comment]
You can also try to compile examples by typing commands like:
```bash
gfortran gtk.f90 gtk-sup.f90 ../examples/julia_pixbuf.f90 `pkg-config --cflags --libs gtk+-2.0`
./a.out

```
But this is a Linux command. I do not know how to adapt it to MacOS.
See also the old (not maintained) test.sh script in the src/ directory.

**Comment by jessica-brown** [comment]
Hi Vincent,

Thanks very much for your reply.
Originally I was using GTK+ 2.24.30, installed via macports
<https://www.macports.org/ports.php?by=name&substr=gtk> (gtk2 in macports).
I also tried using GTK+ 3.20.6 (gtk3) but that produced a similar error.
When I put in the code you sent to me (gfortran gtk.f90 gtk-sup.f90
../examples/julia_pixbuf.f90 `pkg-config --cflags --libs gtk+-2.0`), I got
the following errors:

gtk.f90: No such file or directory
gtk-sup.f90: No such file or directory

I'm not very experienced compiling/installing programs so I'm not sure why
these errors are occurring.

Jessica

**Comment by vmagnin** [comment]
Hi Jessica,
the 2.24.30 is also on my Kubuntu 16.04 Linux distribution. So it is not a problem of version.

The compiling command I gave you must be typed from the `gtk-fortran/src/` directory, which contains those two files.

V.

**Comment by vmagnin** [comment]
Hi Jessica,

I have updated the gtk-fortran/src/test.sh script in the master and gtk3 branches. You can use it to compile the gtk-fortran files and examples and run them. It does not install the gtk-fortran library on your system, but it is a more basic and simple way to use gtk-fortran than the CMake way.

V.

**Comment by vmagnin** [comment]
Hi Jessica,
See the new workaround to issue https://github.com/jerryd/gtk-fortran/issues/89
Just type `make -i` to ignore errors...

**Comment by zbeekman** [comment]
Hi Vincent,

I am hitting the same  error message on macOS: `ld: illegal text-relocation to '_hl_gtk_listn_edit_cb' in CMakeFiles/gtk-fortran_shared.dir/gtk-hl-tree.f90.o from 'lC72' in CMakeFiles/gtk-fortran_shared.dir/gtk-hl-tree.f90.o for architecture x86_64`

This is a gfortran bug having to do with `ISO_C_BINDING`, I believe. I can continue on and not build the shared library on macOS using `make -i`.

**Comment by zbeekman** [comment]
The executable `list_demo` also triggers a similar error:
```
list_demo
ld: illegal text-relocation to '_gtk_main_quit' in /usr/local/lib/libgtk-quartz-2.0.dylib from 'lC0' in CMakeFiles/list_demo.dir/list_demo.f90.o for architecture x86_64
collect2: error: ld returned 1 exit status
```

And with GCC 6.4 (installed via homebrew)  it also ICEs (but 7.1 seems to work fine.... :man_shrugging: ):
```
Scanning dependencies of target gtkbuilder2
[ 65%] Building Fortran object examples/CMakeFiles/gtkbuilder2.dir/gtkbuilder2.f90.o
'
/Users/ibeekman/gtk-fortran/gtk-fortran-16.10.gtk2.24.30/examples/gtkbuilder2.f90:90:0:

   function button2clicked (widget, gdata ) result(ret)  bind(c)

in pp_format, at pretty-print.c:633

Internal compiler error: Error reporting routines re-entered.
gfortran-6: internal compiler error: Abort trap: 6 (program f951)
Please submit a full bug report,
with preprocessed source if appropriate.
```

**Comment by vmagnin** [comment]
I close that issue because it is an old post, but don't hesitate to reopen if the problem persists.
