### ISSUE TITLE
mingw32-make: *** No rule to make target `install'.  Stop.

### ISSUE THREAD

**Issue by drigomen** [jerryd/gtk-fortran#68]
Hi everyone.

I am trying to install gtk-fortran in a win7 x86 machine. After successfully installing all the prerequisites (cmake, sed, wget, gfortran4.8, gtk3, plplot) I execute win32_install.bat but i get the following message:

Configuring incomplete, errors occurred!
mingw32-make: **\* No rule to make target `install'.  Stop.

I know that my gtk3 installation is ok because it works for pygobject and glade. The only environment variable related to gtk-fortran is PKG_CONFIG_PATH set to C:\gtk-fortran-gtk3\src

Do you know what is going on?

**Comment by vmagnin** [comment]
I close that issue because it is an old post, but don't hesitate to reopen if the problem persists.
