### ISSUE TITLE
Preparing for Ubuntu 15.04

### ISSUE THREAD

**Issue by vmagnin** [jerryd/gtk-fortran#75]
With Kubuntu 14.04 32bits:

- using the gtk-fortran library built with Kubuntu 13.10, there was no problem building examples with "make". The examples seems to run fine, except plplot examples:
```~/Bureau/gtk-fortran-03-04-2014-test/build/plplot$ ./hl_plplot8e
 resize         600         600
Requested device extcairo not available```
- generating the gtk-fortran library with cfwrapper.py, I obtain the following messages when building:
```
$ make
Scanning dependencies of target gtk-fortran_shared
[  1%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/glib-auto.f90.o
[  2%] Building Fortran object src/CMakeFiles/gtk-fortran_shared.dir/gtk.f90.o
gtkenums-auto.f90:1122.51:
    Included at /home/vmagnin/Bureau/gtk-fortran-kubuntu14_04/gtk-fortran/src/gtk.f90:31:

    enumerator :: G_SUBPROCESS_FLAGS_STDIN_PIPE = 1u << 0
                                                   1
Error: Syntax error in ENUMERATOR definition at (1)
gtkenums-auto.f90:1123.54:
    Included at /home/vmagnin/Bureau/gtk-fortran-kubuntu14_04/gtk-fortran/src/gtk.f90:31:

    enumerator :: G_SUBPROCESS_FLAGS_STDIN_INHERIT = 1u << 1
                                                      1
Error: Syntax error in ENUMERATOR definition at (1)
gtkenums-auto.f90:1124.52:
    Included at /home/vmagnin/Bureau/gtk-fortran-kubuntu14_04/gtk-fortran/src/gtk.f90:31:

    enumerator :: G_SUBPROCESS_FLAGS_STDOUT_PIPE = 1u << 2
                                                    1
Error: Syntax error in ENUMERATOR definition at (1)
gtkenums-auto.f90:1125.55:
    Included at /home/vmagnin/Bureau/gtk-fortran-kubuntu14_04/gtk-fortran/src/gtk.f90:31:

    enumerator :: G_SUBPROCESS_FLAGS_STDOUT_SILENCE = 1u << 3
                                                       1
Error: Syntax error in ENUMERATOR definition at (1)
gtkenums-auto.f90:1126.52:
    Included at /home/vmagnin/Bureau/gtk-fortran-kubuntu14_04/gtk-fortran/src/gtk.f90:31:

    enumerator :: G_SUBPROCESS_FLAGS_STDERR_PIPE = 1u << 4
                                                    1
Error: Syntax error in ENUMERATOR definition at (1)
gtkenums-auto.f90:1127.55:
    Included at /home/vmagnin/Bureau/gtk-fortran-kubuntu14_04/gtk-fortran/src/gtk.f90:31:

    enumerator :: G_SUBPROCESS_FLAGS_STDERR_SILENCE = 1u << 5
                                                       1
Error: Syntax error in ENUMERATOR definition at (1)
gtkenums-auto.f90:1128.53:
    Included at /home/vmagnin/Bureau/gtk-fortran-kubuntu14_04/gtk-fortran/src/gtk.f90:31:

    enumerator :: G_SUBPROCESS_FLAGS_STDERR_MERGE = 1u << 6
                                                     1
Error: Syntax error in ENUMERATOR definition at (1)
gtkenums-auto.f90:1129.52:
    Included at /home/vmagnin/Bureau/gtk-fortran-kubuntu14_04/gtk-fortran/src/gtk.f90:31:

    enumerator :: G_SUBPROCESS_FLAGS_INHERIT_FDS = 1u << 7
                                                    1
Error: Syntax error in ENUMERATOR definition at (1)
make[3]: *** [src/CMakeFiles/gtk-fortran_shared.dir/gtk.f90.o] Erreur 1
make[2]: *** [src/CMakeFiles/gtk-fortran_shared.dir/gtk.f90.o.provides] Erreur 2
make[1]: *** [src/CMakeFiles/gtk-fortran_shared.dir/all] Erreur 2
make: *** [all] Erreur 2```

**Comment by vmagnin** [comment]
Same problem of course with With Kubuntu 15.04 32bits. The solution is to remove the "u" (unsigned) after each number, by adding a regex in the translate_enums() function of cfwrapper.py.
Something like that (not tested yet):
```python
        parameters[0] = re.sub("\(1u[ ]<<", "\(1[ ]<<", parameters[0])
```

**Comment by vmagnin** [comment]
Hi James,

Under Kubuntu 15.04 64bits, when using "make" I obtain the following error:
```bash
[ 94%] Building Fortran object plplot/CMakeFiles/hl_plplot17e.dir/hl_plplot17e.f90.o
Warning: Nonexistent include directory "/usr/lib/fortran/modules/plplot"
/home/vmagnin/Bureau/gtk-fortran/plplot/hl_plplot17e.f90:50.6:

  use plplot, PI => PL_PI
      1
Fatal Error: Can't open module file 'plplot.mod' for reading at (1): Aucun fichier ou dossier de ce type
plplot/CMakeFiles/hl_plplot17e.dir/build.make:54: recipe for target 'plplot/CMakeFiles/hl_plplot17e.dir/hl_plplot17e.f90.o' failed
make[2]: *** [plplot/CMakeFiles/hl_plplot17e.dir/hl_plplot17e.f90.o] Error 1
CMakeFiles/Makefile2:2010: recipe for target 'plplot/CMakeFiles/hl_plplot17e.dir/all' failed
make[1]: *** [plplot/CMakeFiles/hl_plplot17e.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
```
It seems the path is now:
/usr/lib/x86_64-linux-gnu/fortran/modules/plplot/plplot.mod

James, what should be changed in CMake configuration ?

**Comment by vmagnin** [comment]
Finally, when working with a fresh pull from github CMake detected the new plplot path. There is no build error anymore. 
All examples seems to work (gtk3 branch), even the plplot examples after installing the package plplot12-driver-cairo.

**Comment by jtappin** [comment]
Hi Vincent,
Adding your comments together -- I think that the cmake scripts look in a number of standard places for libs, include files, Fortran modules etc., but once they are written into the configurations and Makefiles they can only be changed by drastic measures. I think actually "rm -r *" in the build directory and a fresh cmake   will suffice when something like that happens.

P.S. There is an issue with library names in plplot 5.11 as the trailing "d" has been dropped, I'll get that sorted shortly  (hopefully tomorrow).
