### ISSUE TITLE
GTK-Fortran + Plplot (Win7 64bits)

### ISSUE THREAD

**Issue by waltbrainerd** [jerryd/gtk-fortran#77]
I compiled and ran (almost) all the plplot examples.

I can't run the GTK/plplot examples. Says it can't
find cairo.

Darius (C::B) says cairo.dll should be in this file.
$ ls install_dll/lib/*0/driversd
mem.dll           svg.dll
mem.driver_info   svg.driver_info
null.dll          wingcc.dll
null.driver_info  wingcc.driver_info
ps.dll            xfig.dll
ps.driver_info    xfig.driver_info

A clue might be the following line in the cmake result:

DRIVERS_LIST: mem;null;ps;svg;wingcc;xfig

which has the drivers in "driversd", but not cairo.dll.

How do I get cairo in the list?

And while we are at it, can plplot make a jpeg file
(for example) that can be saved?

Thanks for the help.

Windows 7 64

**Comment by vmagnin** [comment]
I close that issue because it is an old post, but don't hesitate to reopen if the problem persists.
