### ISSUE TITLE
text views + glade

### ISSUE THREAD

**Issue by waltbrainerd** [jerryd/gtk-fortran#78]
I am trying to use Glade with GTK-Fortran.
I have a window with a box with two widgets, a button to click
and a text box to display text when the button is clicked. I
figured this out using hl_\* commands to build the windows.
Using glade, I can't figure out how to display the text in the
text box. When I use hl_gtk_text_view_insert (which works in
the non-glade version), I get the following errors:

(a.exe:8828): Gtk-CRITICAL **: gtk_text_view_get_buffer: assertion `GTK_IS_TEXT_VIEW (text_view)' failed

(a.exe:8828): Gtk-CRITICAL **: gtk_text_buffer_set_text: assertion `GTK_IS_TEXT_BUFFER (buffer)' failed

Unfortunately, the gtkbuilder examples only write to std out when
the buttons are pushed, so there is no example there to mimic.

Here are the glade files and the program. The commented part
shows how I did it without glade. Sorry for the length--didn't see a
way to attach files to this.

**Comment by vmagnin** [comment]
I close that issue because it is an old post, but don't hesitate to reopen if the problem persists.
