### ISSUE TITLE
Top level CMakeLists.txt has compiler specific options

### ISSUE THREAD

**Issue by IanH0073** [jerryd/gtk-fortran#80]
On the gtk3 branch (and perhaps others), the CMakeLists.txt file in the top level of the source distribution has compiler specific options in it.  Compilers such as Intel Fortran on windows do not understand those hard coded options.  Something like the following might make things a little more portable.

    diff --git a/CMakeLists.txt b/CMakeLists.txt
    index 803b6a0..820c423 100644
    --- a/CMakeLists.txt
    +++ b/CMakeLists.txt
    @@ -49,10 +49,17 @@ message(STATUS "Build type is: ${CMAKE_BUILD_TYPE}")

     # Removed -ffpe-trap=invalid,zero,overflow as it gives a lot of crashes deep
     # in the call stack in Gtk3
    -set(CMAKE_Fortran_FLAGS_DEBUG
    -"-g -pthread -Wall -Wtabs -fcheck=all -fbacktrace -Wno-unused-dummy-argument")
    -set(CMAKE_Fortran_FLAGS_RELEASE
    -"-pthread -O3 -mtune=native -march=native")
    +# FFLAGS depend on the compiler
    +get_filename_component (Fortran_COMPILER_NAME ${CMAKE_Fortran_COMPILER} NAME)
    +
    +if (Fortran_COMPILER_NAME MATCHES "ifort.*" AND CMAKE_HOST_WIN32)
    +else()
    +  # gfortran
    +  set(CMAKE_Fortran_FLAGS_DEBUG
    +  "-g -pthread -Wall -Wtabs -fcheck=all -fbacktrace -Wno-unused-dummy-argument")
    +  set(CMAKE_Fortran_FLAGS_RELEASE
    +  "-pthread -O3 -mtune=native -march=native")
    +endif()

     set(CPACK_PACKAGE_VERSION "0.1.0")
     set(CPACK_PACKAGE_INSTALL_DIRECTORY "gtk3-fortran")

(Depending on what the library does, ifort may want /standard-semantics in there - I am not sure if this can be nominated using more portable CMake properties or similar.)

**Comment by vmagnin** [comment]
Thank you for this remark.
I have now added such a test in my gtk3devel branch, soon to be merged and pushed to gtk3 branch.
