### ISSUE TITLE
Reference to non-standard FDATE() intrinsic in gtkf-sketcher.f90

### ISSUE THREAD

**Issue by IanH0073** [jerryd/gtk-fortran#81]
On the gtk3 branch, the file sketcher/gtkf-sketcher.f90 contains several references to the FDATE intrinsic, which is an extension (albeit common).  A F2003 portable alternative is suggested below.

    diff --git a/sketcher/gtkf-sketcher.f90 b/sketcher/gtkf-sketcher.f90
    index f3fa0ed..9e8273a 100644
    --- a/sketcher/gtkf-sketcher.f90
    +++ b/sketcher/gtkf-sketcher.f90
    @@ -225,6 +225,8 @@ module handlers

       implicit none

    +  private :: fdate
    +
     contains

       subroutine copy_file(source,destination)
    @@ -801,6 +803,17 @@ contains

       end subroutine default_options

    +  function fdate()
    +    character(29) :: fdate
    +    character(8) :: date
    +    character(10) :: time
    +    character(5) :: zone
    +
    +    call date_and_time(date, time, zone)
    +    fdate = date(1:4) // '-' // date(5:6) // '-' // date(7:8)  &
    +        // 'T' // time(1:2) // ':' // time(3:4) // ':' // time(5:10)  &
    +        // zone(1:3) // ':' // zone(4:5)
    +  end function fdate
     end module handlers

     program gtkfsketcher

**Comment by vmagnin** [comment]
Errors obtained when compiling with ifort 2015:
```
../../sketcher/gtkf-sketcher.f90(470): error #6404: This name does not have a type, and must have an explicit type.   [FDATE]
		write(wunit,'(A)')"! "subdir(1:len_trim(subdir))" widget module generated by gtkf-sketcher, "//fdate()
-----------------------------------------------------------------------------------------------------------^
../../sketcher/gtkf-sketcher.f90(470): error #6054: A CHARACTER data type is required in this context.   [FDATE]
		write(wunit,'(A)')"! "subdir(1:len_trim(subdir))" widget module generated by gtkf-sketcher, "//fdate()
-----------------------------------------------------------------------------------------------------------^
../../sketcher/gtkf-sketcher.f90(483): error #6054: A CHARACTER data type is required in this context.   [FDATE]
		write(hunit,'(A)')"! "subdir(1:len_trim(subdir))" handler module generated by gtkf-sketcher, "//fdate()
------------------------------------------------------------------------------------------------------------^
../../sketcher/gtkf-sketcher.f90(499): error #6054: A CHARACTER data type is required in this context.   [FDATE]
	  write(50,'(A)')"! "subdir(1:len_trim(subdir))" main program generated by gtkf-sketcher, "//fdate()
-----------------------------------------------------------------------------------------------------^
compilation aborted for ../../sketcher/gtkf-sketcher.f90 (code 1)
```
FDATE is an extension in gfortran:
https://gcc.gnu.org/onlinedocs/gfortran/FDATE.html

**Comment by vmagnin** [comment]
Thank you Ian,
I have applied your patch in my gtk3devel branch, soon to be merged and pushed to gtk3 branch.
