### ISSUE TITLE
Glade/GTKExtra inegration (windows)

### ISSUE THREAD

**Issue by DrOli** [jerryd/gtk-fortran#86]
I can't seem to be able integrate GTKExtra 3.0.5 into Glade 3.8.5 (built on Windows with MingW, and appears to work outside of Glade).  I have tried to make/install with something like

./configure --prefix=${LOCALDESTDIR} --enable-glade && \
make && \
make install

but it aborts on: "configure: error: Package requirements (gladeui-1.0 >= 3.6) were not met:"

There are gladeui dll's on the path, but (what little I understand about this) the pkg-config files are not created or something to that effect.

In any case, any assistance with the Glade/GTKExtra integration would be greatly appreciated.

BTW, I can get the GTKExtra "widget/icons" to show up in Glade (e.g. put xml in share/catalog dir, etc), and can "insert" a GTKExtra "widget/sheet" into a container as a "gtk sheet".

My xml has been edited to reflect that it should be using the appropriate win32 lib (.dll), and the GLADE_CATALOG_PATH and GLADE_MODULE_PATH env vars have been set in WinXP to be (as far as I can tell) the equivalent of the Linux env/pather (e.g.  /home/devel/Z/gtk changed to my install equivalent)

Unfortunately, it does "nothing" beyond that (i.e. the inserted widgets do nothing), since, presumably the linkage to libs etc, perhaps needed to be created by  --enable-glade, are not present or where it expects them, even though I have the GTKExtra libs/dll's on the path etc etc.

You comments would be greatly appreciated.

**Comment by vmagnin** [comment]
Theoretically, cfwrapper.py could be adapted to other C header files, to wrap other C libraries than GTK, but with around 10000 functions, gtk-fortran needs already sufficient work to maintain. So I do not plan to wrap other libraries.
