### ISSUE TITLE
GTK-Fortran GTKSheet crash

### ISSUE THREAD

**Issue by DrOli** [jerryd/gtk-fortran#87]
I have implemented a basic test/demo of the GTKExtra sheet following the example here (http://gtkextra.sourceforge.net/docs/tutorial/gtksheet/gtksheet_howto.html) on WinXP64.

The basic example works.

I have added some signal/callbacks to interact with the sheet.  Some (signal/callback) functions work correctly (e.g. change sheet colour, set text in a chosen cell, etc)

I use:

    call g_signal_connect( sheet, "activate"//c_null_char, c_funloc(signal_sheet_clicked) )

to interact with the sheet.

The callback was copied from one of the gtk-fortran examples, and takes the form

    function signal_sheet_clicked(widgetV, gdataV) result(ret) bind(c)
        !
        type(c_ptr), Value  :: widgetV
	!
        type(c_ptr), Value  :: gdataV
		
	:
	... do stuff

Notice that the widgetV var is declared to be passed by Value.  If it is NOT passed by Value, then NONE of the sheet functions work, and they each complain:

** (gtk_demo.exe:2156): CRITICAL **: gtk_sheet_get_active_cell: assertion 'GTK_IS_SHEET(sheet)' failed

Passing by Value allows most, but not all, sheet functions to work correctly.

Unfortunately, passing by Value CRASHES (seg fault, etc) important functions.  For example:

        Call gtk_sheet_get_active_Cell(widgetV, iRow_Ptr, iCol_Ptr)

CRASHES immediately on entry (SIGSEGV), if widgetV is passed by Value into the signal_sheet_clicked() func.  If widgetV is NOT by Value, then it fails to process the function on the "assertion" error.

Somewhat similar:

       iReturn = gtk_sheet_get_selection(widgetV, state_Ptr, range_Ptr)

complains of the "assertion", returns rubbish for state_ptr, and range_ptr, then the s/r continues to process remaining statements, but CRASHES at the point that the function signal_sheet_clicked() ends/returns (commenting out that call to that gtk func obviates that crash).

On the face of it, the sheet functions that need to "return something" appear to be problematic.

I have tried a huge number of combinations/permutations of different ways to pass the sheet/widget vars, in combination with variations of the C/Fortran bindings in GTKExtra-Auto.f90.

... nothing worked for these s/r's.

Any assistance would be greatly appreciated as NOT being able to retrieve basic sheet info (e.g. the row/col/sheet numbers for the current/active cell, or ranges, etc) pretty much makes the GTKSheet process useless/intractable for a wide range of applications.

Many thanks

DrO

**Comment by DrOli** [comment]
I may have narrowed the problem a little.  

The call to gtk_sheet_get_active_Cell() is via a "signal func" such as:

    Function signal_Func(widgetV, gdataV)
	...
	Type(c_Ptr), Value	:: widgetV, gdataV
	Type(c_Ptr)		:: row, column
	Integer(c_Int)		:: nCol
	...
        Call gtk_sheet_get_active_Cell(widgetV, iRow_Ptr, iCol_Ptr)	 ! this CRASHES or FAILS, depending on "variation", see below
	..
	..
	! some additional results
	..
	iReturn = gtk_sheet_get_selection(widgetV, state_Ptr, range_Ptr) ! this CRASHES or FAILS, depending on "variation"
	..
	..
	Call gtk_sheet_set_cell_text(sheet = widgetV, row = iRow, col = iCol, text = "Rubbish"//c_null_char)	! this works perfectly
	..
	Call gtk_sheet_set_background(widgetV, color = Colour_Ptr)	! this works perfectly
	..
	nCols = gtk_sheet_get_columns_count(widgetV)			! this works perfectly
	..
	.. do stuff
    End Function

That call is via a binding as per (from GTKExtra-Auto.f90):

    subroutine gtk_sheet_get_active_cell(sheet, row, column) bind(c)
        use iso_c_binding, only: c_ptr, c_Int
        type(c_ptr), Value      :: sheet
        type(c_ptr), value 	:: row
        type(c_ptr), value 	:: column
    end subroutine

widgetV is a sheet pointer that works with other sheet functions, and must be  passed by Value to func signal_Func(), otherwise all of the sheet functions fails on the "assertion" issue.

But, in that case, gtk_sheet_get_active_cell() crashes on seg fault etc.

However, if in the bindings, the following is used instead:

    subroutine gtk_sheet_get_active_cell(sheet, row, column) bind(c)
        use iso_c_binding, only: c_ptr, c_Int
        type(c_ptr), Value      :: sheet
        type(c_ptr)	 	:: row
        type(c_ptr)	 	:: column
    end subroutine

that is, the row and column vars are passed by ref instead of Value, then it does NOT crash and does NOT fail on the "assertion" issue.

Unfortunately, on return the c_Ptr's row and column contain garbage (as they always have thus far).


I have tested many permutations and combinations, this seems to be the "closest" I can get to "working" implementation

... but clearly it is still not working as required.

I don't know enough about the C-side of GTK/GTKExtra though I have examined the GTKSheet.c and .h files, and can't see how to fix this problem, as I can't see why it is not capable of setting those values on return.

... though it is this by Value vs. by Ref of c_Ptrs row and column that seems central.

... indeed, it is the same sort of problem with gtk_sheet_get_selection(widgetV, state_Ptr, range_Ptr), where the c_Ptr's state_Ptr, and range_Ptr return garbage.

Your assistance would be greatly appreciated,  particularly as it is NOT possible to do anything meaningful with a "sheet" if one cannot obtain important information from it.


Cheers

DrO

**Comment by vmagnin** [comment]
Theoretically, cfwrapper.py could be adapted to other C header files, to wrap other C libraries than GTK, but with around 10000 functions, gtk-fortran needs already sufficient work to maintain. So I do not plan to wrap other libraries.
