### ISSUE TITLE
GTK/GTKExtra/GTK-Fortran on Windows

### ISSUE THREAD

**Issue by DrOli** [jerryd/gtk-fortran#88]
I can now build/install from source almost everything to arrive at a full GTK/Glade/GTKExtra installation with Glade integration on Windows.  There are various issues, but for the most part it works.
 
Keeping in mind that the (substantial) extra work is primarily to have GTKExtra implementation, John and GerryD's mostly Win binaries approach may still be preferable by many.  Though, I can tell you that the Win binary approach is less stable compared to the full build/install approach (even without GTKExtra).
 
The short explanation of why this is now possible with "relative" ease is that the latest version of MingW64-32 (not the standard MingW) overcome many of the package/version collisions. 
 
Roughly speaking, using Ingar's method (http://ingar.satgnu.net/devenv/mingw32/base.html), with some updates/fixes/patches, provides a "relatively" manageable process to a full build install of GTK/Glade/GTKExtra on Windows/MingW64-32, with all the latest packages.  

I am working on a detailed note for the process.
 
Also, in addition to GTK/Glade issues, there are also GTK-Fortran issues/pathologies, especially with GTKExtra.  I have made substantial progress here too.  Though, much of the progress required writing additional C and Fortran code, some of which must be integrated with GTKExtra package (before it is built/installed) and compiled/linked into the GTKExtra libs.
 
I have included below a file I named gtksheetf90.c (and which must be "included" in the GTKExtra package for build/install), which illustrates a fix for some of the pathologies, but also demonstrates the need for assistance on other pathologies.
 
There are various other types of issues such those relating to the pros/cons of using GTKExtra 3.0.5 vs. 3.1.3, issue relating to distribution of apps to other machines/Windows versions, etc., but that's for later.

gtksheetf90.c ------------------------------------------------

/*
                GTKExtra/GTK-Fortan "Pathologies" Helper File
                =============================================

                        DrO, May, 2015

        This file was created to help overcome some PATHOLOGIES in using GTKExtra
        with GTK-Fortran.

        Some, BUT NOT ALL, pathologies have been overcome.  My C-skills are much worse
        compared to my Fortran-skills, and I expect somebody with good C-skills, and
        better understanding of mixed-language C/Fortran programming may be able
        to IMPROVE CONSIDERABLY on these problems/solutions.

        The testing, thus far has been on Windows ONLY.

        See USAGE, and KNOWN ISSUES - Cry for Help further below
            =====      ===========================

        The PRIMARY pathology is the inability of the C/Fortran binding to return
        certain types of results produced on the C-side.  For example, the void

                void gtk_sheet_get_active_cell(*sheet, gint *row, gint *colunm);

        Cannot return the row/column values to the Fortan side. Indeed, calling this s/r
        WILL CRASH the Fortran/GTK app.

        I wrote C versions of my test codes also, which do not have these problems, of course.

        Clearly, a vast number of GTKSheet programmes will need this and other pathological s/r's.

        Many variations have been tested, and to date ONLY ONE PARTIAL solution has been found.
        Some of the offending bindings can be circumvented with "C-side wrapper functions".  For example
        the s/r above can be augmented (effectively replaced), with something like

                gint gtk_sheet_get_active_cell_row_f90(*sheet)
                {
                     g_return_if_fail(sheet != NULL);
                     g_return_if_fail(GTK_IS_SHEET(sheet));

                     gint row = sheet->active_cell.row;
                     return row;
                }

        USAGE
        =====

        1) Put a copy of this file into the GTKExtra "build" Dir, the same Dir where gtksheet.c reside,
        something like ...build\gtkextra-3.0.5\gtkextra\, assuming ver 3.0.5

        2) Edit gtksheet.c by adding the following line approx 332 for ver 3.0.5
        or around line 350 for ver 3.1.3 (after the other includes/defines):

                #include "gtksheetf90.c"

        ==> Then re-compile/build/make/install GTKExtra from source

        3) On the Fortran-side, add the appropriate bindings/interfaces to an .f90 or to the already
        existing GTK-Fortran f90's/modules.  For example, the above would be implemented as:

                Function gtk_sheet_get_active_cell_row_f90(sheet) bind(c)
                    Use iso_c_binding, only: c_ptr, c_Int
                    Integer(c_Int)            :: gtk_sheet_get_active_cell_row_f90
                    Type(c_ptr), Value        :: sheet
                End Function gtk_sheet_get_active_cell_row_f90

        Then, of course, this Function must be made available to your Fortran code via the usual Use etc process.

        For example, a signal processing routine for managing clicking on a cell in a sheet might take
        the following, assuming that all these "new/circumvent" s/r's are in a Module called GTKExtra_ExtraMod

        Function signal_sheet_click(sheet, gdata)
            !
            Use Iso_C_Binding
            Use GTKExtra_ExtraMod
            !
            Implicit None
            !
            Type(c_Ptr), Value         :: sheet
            Type(c_Ptr)                :: gdata
            !
            Integer(c_Int)             :: iRow, iCol
            !
            !Type(c_Ptr)               :: iRowPtr, iColPtr              <== the expected/normal vars, WONT work
            !
            !Call gtk_sheet_get_active_cell(sheet, iRowPtr, iRowCol)    <== this "normal/expected" binding will CRASH your code
            !
            ! Instead, use the "workaround/wrappers"
            !
            iRow = gtk_sheet_get_active_cell_row_f90(sheet)
            iCol = gtk_sheet_get_active_cell_column_f90(sheet)
            !
                ... etc

        End Function signal_sheet_click

        KNOWN ISSUES and CRY FOR HELP
        =============================

        1) Obviously, if there is a better way of doing the above, it would be nice to know.

        2) Some PATHOLOGIES CANNOT be circumvented this way.  In particular, gtk functions/voids
        that deal with/return GTK internally defined structures are STILL PATHOLOGICAL.  For example:

            gboolean gtk_sheet_get_attributes (GtkSheet *sheet,
                                               gint row,
                                               gint col,
                                               GtkSheetCellAttr *attributes);

        is supposed to make available the results via the variable *attributes, which has Fortran
        equivalent structure of:

            Type, bind(c) ::  GtkSheetAttrType
                Integer(c_Int)  :: Sheet_Foreground
                Integer(c_Int)  :: Sheet_Background
                Integer(c_Int)  :: Sheet_Font
                Integer(c_Int)  :: Sheet_Justification
                Integer(c_Int)  :: Sheet_Border
                Integer(c_Int)  :: Sheet_Border_Color
                Integer(c_Int)  :: Sheet_Is_Editable
                Integer(c_Int)  :: Sheet_Is_Visible
            End Type GtkSheetAttrType

        But the GTK-Fortran binding of this function requires declaring the attributes variable as:

            Type(c_Ptr)     :: attributes

        This fails/CRASHES.  Creating a "wrapper", as above, does NOT work since having a wrapper
        function on the C-Side of the form:

            GtkSheetCellAttr *gtk_sheet_get_attributes_f90 (GtkSheet *sheet,
                                               gint row,
                                               gint col,
                                               );

        does NOT have the effect, as it did before, of converting the return value to something
        that the C-Fortran binding can handle properly.

        Thus, all the GTK functions/voids that return any complex pointers FAIL/CRASH on the
        Fortran-side.

        ==> THIS REQUIRES IMMEDIATE EXPERT ATTENTION.

        3) Although perhaps not essential for reasons explained else where, GTK relies on
        CPP macros, instead of "proper" functions, to perform important duties.  For example,
        the GTK macros GTK_SHEET(obj), or GTK_CONTAINER() etc, may be of some use on
        Fortran-side, but currently NOT available in GTK-Fortran.

        Wrappers have been tested for these, such as the example wrapper gtk_sheet_from_widget_f90()
        intended to provide connectivity to the Fortran-side by the usual Function/Interface/binding
        process.

        ... it does not work at the moment, but it has lower priority compared to the above, as
        explained else where in DrO's Notes.

*/

//ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ             // DrO
// NOTE: the next few func's/void's are provide an interface possibility for some CPP macro              // DrO
//       required on the Fortran side (accessible by the usual Interface/Bind(c) approach               // DrO
//
//      REMEMBER, the entire GTKExtra package MUST BE ENTIRELY RE-BUILT from scratch                    // DrO
//      every time one of these elements is created                                                      // DrO
//
//      Might be better if a separate file could be used, but then all the configure/make
//      bits would need to be re-written
//
//ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ             // DrO

//
// Interface to GTK_SHEET(obj) CPP macro                                      // DrO
// -------------------------------------                                      // DrO
//
// takes widget is input, and produces outpur sheet                           // DrO

void                                                                          // DrO
gtk_sheet_from_widget_f90(GtkWidget *widget, GtkSheet *sheet, gint iSuccess)  // DrO
{                                                                             // DrO
    iSuccess = -1;                                                             // DrO
//    sheet = -1;                                                               // DrO
    //
    g_return_if_fail(widget!= NULL);                                          // DrO
    sheet = GTK_SHEET(widget);                 // NOTE: need to check which of these is correct; sheet = ... ; or *sheet = ...                   // DrO
//??    *sheet = GTK_SHEET(widget);                   // NOTE: need to check which of these is correct; sheet = ... ; or *sheet = ...                   // DrO
    g_return_if_fail(GTK_IS_SHEET(sheet));                                    // DrO
    //
    iSuccess = 0;                                                             // DrO
}

/*
        NOTE: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ           // DrO
        This is a special version of the void gtk_sheet_get_active_cell() above         // DrO
        to permit f90 binding/integration, as the raw version above seems to            // DrO
        have FATAL/PATHOLOGICAL problems passing back the gint *row, gint * column      // DrO
        pointers.                                                                       // DrO

        INSTEAD, create a "wrapper" that return just gint row, and gint column          // DrO
        as values, instead of pointers.                                                 // DrO

        XXXXXXXXXXXXXXXXXXXXXXX this approach seems to be TROUBLESOME                   // DrO
        XXXXXXXXXXXXXXXXXXXXXXX TRY Functions instead of void's                         // DrO
*/
void                                                                                    // DrO
//gtk_sheet_get_active_cell_f90(GtkSheet *sheet, gint row, gint column)                   // DrO
gtk_sheet_get_active_cell_f90(GtkSheet *sheet, guint row, guint column)                   // DrO
{                                                                                       // DrO

    row = 0;                                                                            // DrO
    column = 0;                                                                         // DrO

    g_return_if_fail(sheet != NULL);                                                     // DrO
    g_return_if_fail(GTK_IS_SHEET(sheet));                                               // DrO

    // now call "actual" s/r                                                             // DrO

    gint *rowPtr;                                                                        // DrO
    gint *columnPtr;                                                                     // DrO

//??    gtk_sheet_get_active_cell(sheet, &rowPtr, &columnPtr);                               // DrO
//>>    gtk_sheet_get_active_cell(sheet, rowPtr, columnPtr);                               // DrO

    // ALTERNATE VERSION

    row = sheet->active_cell.row;                                                       // DrO
    column = sheet->active_cell.col;                                                    // DrO
//??    row = *rowPtr;                                                                        // DrO
//??    column = *columnPtr;                                                                  // DrO
}                                                                                       // DrO

/*
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         // DrO
        SPECIAL Function variant to get Active Cell Row for f90 integration             // DrO
        due to problems with void gtk_sheet_get_active_cell()                           // Dro
        ........ see below for Active Cell Column                                       // DrO
*/

gint                                                                                    // DrO
gtk_sheet_get_active_cell_row_f90(GtkSheet *sheet)                                      // DrO
{                                                                                       // Dro
    g_return_if_fail(sheet != NULL);                                                    // Dro
    g_return_if_fail(GTK_IS_SHEET(sheet));                                              // Dro

//    *row = sheet->active_cell.row;
    gint row = sheet->active_cell.row;
//    *column = sheet->active_cell.col;                                                 // Dro
//    return *row;                                                                      // DrO
    return row;                                                                         // DrO
}                                                                                       // DrO

/*
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         // DrO
        SPECIAL Function variant to get Active Cell Row for f90 integration             // DrO
        due to problems with void gtk_sheet_get_active_cell()                           // Dro
        ........ see below for Active Cell Column                                       // DrO
*/

gint                                                                                    // DrO
gtk_sheet_get_active_cell_column_f90(GtkSheet *sheet)                                      // DrO
{                                                                                       // Dro
    g_return_if_fail(sheet != NULL);                                                    // Dro
    g_return_if_fail(GTK_IS_SHEET(sheet));                                              // Dro

//    *row = sheet->active_cell.row;
//    row = sheet->active_cell.row;
//    *column = sheet->active_cell.col;                                                 // Dro
    gint column = sheet->active_cell.col;                                                 // Dro
//    return *row;                                                                      // DrO
    return column;                                                                         // DrO
}                                                                                       // DrO

**Comment by DrOli** [comment]
oops, everything after the line

gtksheetf90.c ------------------------------------------------

in the above is a single file, but this web page has formatted it into multiple blocks ... not sure how to fix that.

**Comment by vmagnin** [comment]
Theoretically, cfwrapper.py could be adapted to other C header files, to wrap other C libraries than GTK, but with around 10000 functions, gtk-fortran needs already sufficient work to maintain. So I do not plan to wrap other libraries.
