### ISSUE TITLE
Noob problem: GTK-Fortran 3 on Windows 8

### ISSUE THREAD

**Issue by jknicely** [jerryd/gtk-fortran#90]
I would like to make use of GTK-Fortran to create a GUI. I have installed the pre-requisites (gfortran, gtk3, cmake, sed). I have downloaded GTK-Fortran from the link on the right side of the page on https://github.com/jerryd/gtk-fortran. 
As far as I can tell, all I have left to do is install GTK-Fortran. The install instructions say to do something with Cmake, but I have never used Cmake before and have no idea what it means, other than to create a folder called "build". The documentation and forums on it I find don't make what I'm supposed to do any clearer. 

1) Could someone explain to me in painfully explicit steps what I am supposed to do with Cmake to make this work?
An example would be greatly appreciated. IDK if it matters, but I have my GTK folder under C, and the GTK-Fortran folder inside of GTK (the address of the GTK-Fortran looks like "C:\GTK\gtk-fortran-master", where gtk-fortran-master is the name of my GTK-Fortran folder). 
I have tried creating "build" in the gtk-fortran-master folder and invoking cmake with the CMakeLists.txt, but I get the following which ends in an error. 

```
C:\GTK\gtk-fortran-master\build>cmake ../CMakeLists.txt
CMake Warning at CMakeLists.txt:30 (project):
  To use the NMake generator, cmake must be run from a shell that can use the
  compiler cl from the command line.  This environment does not contain
  INCLUDE, LIB, or LIBPATH, and these must be set for the cl compiler to
  work.

-- The Fortran compiler identification is GNU
CMake Warning at C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/Platform/W
indows-GNU.cmake:64 (enable_language):
  To use the NMake generator, cmake must be run from a shell that can use the
  compiler cl from the command line.  This environment does not contain
  INCLUDE, LIB, or LIBPATH, and these must be set for the cl compiler to
  work.
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/Platform/Windows-GNU-Fort
ran.cmake:1 (include)
  C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/CMakeFortranInformation.c
make:33 (include)
  CMakeLists.txt:30 (project)

CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/Platform/Win
dows-GNU.cmake:64 (enable_language):
  No CMAKE_RC_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "RC" or the CMake cache entry CMAKE_RC_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/Platform/Windows-GNU-Fort
ran.cmake:1 (include)
  C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/CMakeFortranInformation.c
make:33 (include)
  CMakeLists.txt:30 (project)

-- Configuring incomplete, errors occurred!
See also "C:/GTK/gtk-fortran-master/CMakeFiles/CMakeOutput.log".
```

2) Alternately, I am considering finding all of the GTK-Fortran .f90 files, compiling them into a single library, and then compiling that with my fortran files whenever I need to use something from GTK-Fortran. 
Something along the lines of 

```
gfortran -c file1.f90 file2.f90 ...
ar r lib_gtk-fortran.a file1.0 file2.0 ...
gfortran mycode.f90 -lib_gtk-fortran
```

Would this be a valid method? Would this be better than using Cmake?

UPDATE - 18 June 2015
I tried option 2) and it failed. I compiled all of the .f90 files, then put the resulting .o and .mod files into the library lib_gtk-fortran.a. When I tried to compile the example gtkhello2.f90 with my library (and all of the other necessary ones), it gave an error stating gtk.mod was not found. gtk.mod is listed in the library, so I'm not sure what's going on with that (I don't know much about modules). 
This made me try compiling gtkhello2.f90 in the same directory as all of the .o & .mod files. This compiles. However, the executable fails to run correctly. It creates a window with the title 

```
a.exe - Entry Point Not Found
```

and a message stating 

```
The procedure entry point g_array_set_clear_func could not be located in the dynamic link 
library C:\GTK\bin\libgtk-3-0.dll. 
```

My first thought was that it might be deprecated, but I have been unable to find it in the list of deprecated GTK functions.

**Comment by vmagnin** [comment]
Dear jknicely,

welcome to the tiny world of gtk-fortran. All administrators of this site are Linux users, so I can not help you concerning Windows stuff. But recently, the user DrOli has worked hard to install and use gtk-fortran under Windows: https://github.com/jerryd/gtk-fortran/issues/84

Concerning the g_array_set_clear_func function, it is not part of the GTK lib but of GLib. So you need a file like libglibXXXXX.dll. See: http://www.gtk.org/download/win32.php

Your option 2) is a basic solution that should work. I remember that some years ago I tried successfully under Windows commands like:
```bash
gfortran -c glib-auto.f90 gtk.f90 gtk-sup.f90 myprogram.f90 atk-auto.f90 cairo-auto.f90 gdk-auto.f90 gdk-pixbuf-auto.f90 pango-auto.f90 -L. -llibgtk-win32-2.0-0 -llibgdk-win32-2.0-0 -llibgobject-2.0-0 -llibgdk_pixbuf-2.0-0 -llibcairo-2
```

The point in the option -L. implies that all the needed dll should be put in the same directory as all the f90 files.

**Comment by vmagnin** [comment]
I close that issue because it is an old post, but don't hesitate to reopen if the problem persists.
